# This is a basic workflow to help you get started with Actions

name: Java CI with Maven and Cucumber

on:
  push:
    branches: [ DineshGitHubAction ]
  pull_request:
    branches: [ DineshGitHubAction ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B clean install

      - name: Run Cucumber Tests
        run: mvn test -Dcucumber.options="--plugin pretty"

